ORDERS = [
    {"id":"CS-10291","customer":"Ali Khan","city":"Lahore","amount":8500,"previous_orders":0,"successful_deliveries":0,"rto_count":0,"address_similarity":0.31,"phone_reuse":2,"delivery_zone_risk":0.82,"product":"Smart Watch","hour":1,"decision":"review"},
    {"id":"CS-10290","customer":"Hamza Ahmed","city":"Islamabad","amount":2100,"previous_orders":8,"successful_deliveries":8,"rto_count":0,"address_similarity":0.94,"phone_reuse":1,"delivery_zone_risk":0.12,"product":"T-Shirt","hour":18,"decision":"dispatch"},
    {"id":"CS-10289","customer":"Ahmed Raza","city":"Karachi","amount":5900,"previous_orders":3,"successful_deliveries":2,"rto_count":1,"address_similarity":0.61,"phone_reuse":1,"delivery_zone_risk":0.55,"product":"Headphones","hour":20,"decision":"review"},
    {"id":"CS-10288","customer":"Sana Malik","city":"Rawalpindi","amount":3400,"previous_orders":12,"successful_deliveries":11,"rto_count":1,"address_similarity":0.91,"phone_reuse":1,"delivery_zone_risk":0.22,"product":"Shoes","hour":16,"decision":"dispatch"},
    {"id":"CS-10287","customer":"Usman Shah","city":"Peshawar","amount":12500,"previous_orders":1,"successful_deliveries":0,"rto_count":0,"address_similarity":0.38,"phone_reuse":3,"delivery_zone_risk":0.76,"product":"Gaming Console","hour":2,"decision":"flagged"},
    {"id":"CS-10286","customer":"Ayesha Noor","city":"Faisalabad","amount":1800,"previous_orders":5,"successful_deliveries":5,"rto_count":0,"address_similarity":0.97,"phone_reuse":1,"delivery_zone_risk":0.18,"product":"Skincare","hour":13,"decision":"dispatch"},
    {"id":"CS-10285","customer":"Bilal Hassan","city":"Multan","amount":7600,"previous_orders":2,"successful_deliveries":1,"rto_count":1,"address_similarity":0.52,"phone_reuse":2,"delivery_zone_risk":0.68,"product":"Sneakers","hour":23,"decision":"review"},
    {"id":"CS-10284","customer":"Mariam Iqbal","city":"Islamabad","amount":2900,"previous_orders":10,"successful_deliveries":10,"rto_count":0,"address_similarity":0.96,"phone_reuse":1,"delivery_zone_risk":0.11,"product":"Perfume","hour":15,"decision":"dispatch"},
    {"id":"CS-10283","customer":"Zain Ali","city":"Karachi","amount":9900,"previous_orders":1,"successful_deliveries":0,"rto_count":0,"address_similarity":0.44,"phone_reuse":2,"delivery_zone_risk":0.71,"product":"Tablet","hour":0,"decision":"flagged"},
    {"id":"CS-10282","customer":"Hira Khan","city":"Lahore","amount":4200,"previous_orders":6,"successful_deliveries":5,"rto_count":1,"address_similarity":0.78,"phone_reuse":1,"delivery_zone_risk":0.38,"product":"Handbag","hour":19,"decision":"review"},
]
